name: Git Checkout repository manually - test

on:
  push:
    branches: 
      - master

jobs:
  git-clone-repository:
    runs-on: ubuntu-latest

    # the following are JOB level/scope environment variables
    env:
      DOCKERHUB_IMAGE: simple-nginx
      # If DOCKERHUB_USERNAME is setup in github secrets, 
      #   then local DOCKERHUB_USERNAME can also set as:
      # DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_USERNAME: kamranazeem
      # The DOCKER_CLI_EXPERIMENTAL needs to exist at job level,
      #   because it is needed in two separate steps.
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
    - name: Checkout code - manually
      # uses: actions/checkout@v2
      env:
        FETCH_DEPTH: 1
      run: |
        # A --depth=1 fetch just gets the branch tips and no prior history.
        #   If you want everything/full repo, use depth=0
        git init .
        git remote add origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
        git fetch --prune --progress --no-recurse-submodules --depth=${FETCH_DEPTH} origin
        pwd
        ls -l
        git log
        echo "---------------------------------------------"

    - name: Setup correct SHORT_x variables
      id: prep
      run: |
        pwd
        ls -l
        echo "-------------------------------------------------------"
        # The SHORT_REF and SHORT_HASH cannot be defined at job level,
        #   because they only exist **after** the code is checked out. 
        SHORT_REF=$(basename ${GITHUB_REF})
        SHORT_HASH=${GITHUB_SHA::7}
